### ISSUE TITLE
User namespace regex must be an exact prefix like '@irc_.*' that includes the separator character (_ or /).

### ISSUE THREAD

**Issue by Ulrar** [hifi/heisenbridge#248]
Hi,

Updated to the latest docker image this morning and the bridge won't start anymore : 

```
User namespace regex must be an exact prefix like '@irc_.*' that includes the separator character (_ or /).
```

My config hasn't changed : 
```
id: heisenbridge
url: http://...
as_token: ...
hs_token: ...
rate_limited: false
sender_localpart: heisenbridge
namespaces:
  users:
  - regex: '@irc_.*'
    exclusive: true
  aliases: []
  rooms: []
```

I've rolled back to 1.14.0 for now which is working fine.
Thanks
